services:
  - type: web
    name: sui-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.14


