services:
  - type: web
    name: sui-backend
    env: python
    rootDir: backend
    buildCommand: |
      echo "python-3.11.14" > runtime.txt
      cat runtime.txt
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    plan: free
